### ISSUE TITLE
Cannot build on Windows with go 1.26rc2

### ISSUE THREAD

**Issue by clin1234** [zmap/zcrypto#473]
```
go install github.com/zmap/zannotate/cmd/...@master
go: downloading github.com/zmap/zannotate v0.0.0-20260129235047-0c78c5a2075e
go: downloading github.com/zmap/dns v1.1.70
# github.com/zmap/zcrypto/ct/x509
C:\Users\שזדס\go\pkg\mod\github.com\zmap\zcrypto@v0.0.0-20250416162916-8ff8dfaa718d\ct\x509\root_windows.go:112:20: cannot use uintptr(unsafe.Pointer(sslPara)) (value of type uintptr) as syscall.Pointer value in struct literal
# github.com/zmap/zcrypto/x509
C:\Users\שזדס\go\pkg\mod\github.com\zmap\zcrypto@v0.0.0-20250416162916-8ff8dfaa718d\x509\root.go:27:32: undefined: loadSystemRoots

go install github.com/zmap/zgrab2/cmd/zgrab2@master
go: downloading github.com/zmap/zgrab2 v1.0.1-0.20260112222927-062ec5e6030e
go: downloading github.com/zmap/zflags v1.4.0-beta.1.0.20251126025438-ec78c6d2f8e9
go: downloading github.com/zmap/zcrypto v0.0.0-20250618174828-7ca6a82cf2d4
go: downloading github.com/weppos/publicsuffix-go v0.40.3-0.20250617082559-9b2e24a9e482
# github.com/zmap/zcrypto/ct/x509
go\pkg\mod\github.com\zmap\zcrypto@v0.0.0-20250618174828-7ca6a82cf2d4\ct\x509\root_windows.go:112:20: cannot use uintptr(unsafe.Pointer(sslPara)) (value of type uintptr) as syscall.Pointer value in struct literal
# github.com/zmap/zcrypto/x509
go\pkg\mod\github.com\zmap\zcrypto@v0.0.0-20250618174828-7ca6a82cf2d4\x509\root.go:27:32: undefined: loadSystemRoots
```

**Comment by clin1234** [comment]
Still occurs:

```
❯ go install github.com/zmap/zannotate/cmd/...@master
go: downloading github.com/zmap/zannotate v0.0.0-20260129235047-0c78c5a2075e
go: downloading github.com/zmap/dns v1.1.70
go: downloading github.com/zmap/go-iptree v0.0.0-20251001212402-0a55a77d6804
go: downloading github.com/zmap/zdns/v2 v2.0.5
go: downloading github.com/osrg/gobgp/v3 v3.37.0
go: downloading github.com/json-iterator/go v1.1.12
go: downloading github.com/sirupsen/logrus v1.9.4
go: downloading github.com/oschwald/geoip2-golang v1.13.0
go: downloading github.com/oschwald/maxminddb-golang/v2 v2.1.1
go: downloading golang.org/x/sys v0.39.0
go: downloading github.com/asergeyev/nradix v0.0.0-20220715161825-e451993e425c
go: downloading github.com/modern-go/reflect2 v1.0.2
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/zmap/go-dns-root-anchors v0.0.0-20250415191259-6d65fb878756
go: downloading github.com/zmap/zgrab2 v0.2.0
go: downloading github.com/zmap/zcrypto v0.0.0-20250416162916-8ff8dfaa718d
go: downloading github.com/weppos/publicsuffix-go v0.40.3-0.20250311103038-7794c8c0723b
go: downloading github.com/zmap/zflags v1.4.0-beta.1.0.20200204220219-9d95409821b6
go: downloading golang.org/x/text v0.32.0
go: downloading github.com/censys/cidranger v1.1.3
go: downloading github.com/prometheus/client_golang v1.22.0
go: downloading github.com/prometheus/common v0.63.0
go: downloading github.com/prometheus/client_model v0.6.2
go: downloading google.golang.org/protobuf v1.36.6
go: downloading github.com/munnerz/goautoneg v0.0.0-20191010083416-a7dc8b61c822
# github.com/zmap/zcrypto/ct/x509
C:\Users\שזדס\go\pkg\mod\github.com\zmap\zcrypto@v0.0.0-20250416162916-8ff8dfaa718d\ct\x509\root_windows.go:112:20: cannot use uintptr(unsafe.Pointer(sslPara)) (value of type uintptr) as syscall.Pointer value in struct literal
# github.com/zmap/zcrypto/x509
C:\Users\שזדס\go\pkg\mod\github.com\zmap\zcrypto@v0.0.0-20250416162916-8ff8dfaa718d\x509\root.go:27:32: undefined: loadSystemRoots

❯ go install github.com/zmap/zlint/v3/cmd/...@master
go: downloading github.com/zmap/zlint v2.2.2-0.20260301155658-145bd268839e+incompatible
go: downloading github.com/zmap/zlint/v3 v3.6.9-0.20260301155658-145bd268839e
go: downloading github.com/zmap/zcrypto v0.0.0-20251227215108-5ca1211d486b
go: downloading github.com/pelletier/go-toml v1.9.5
go: downloading github.com/weppos/publicsuffix-go v0.50.1
# github.com/zmap/zcrypto/x509
go\pkg\mod\github.com\zmap\zcrypto@v0.0.0-20251227215108-5ca1211d486b\x509\root.go:27:32: undefined: loadSystemRoots
```
